In [12]:
import timeit

# 定义一个简单的Python函数
def simple_function(x):
    return x * x + 2 * x + 1

# 使用tf.function装饰器将其转换为TensorFlow函数
@tf.function
def tf_simple_function(x):
    return x * x + 2 * x + 1

# 测试执行性能
input_data = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)

# 测试普通Python函数的执行时间
start_time = timeit.default_timer()
_ = simple_function(input_data)
elapsed_time_python = timeit.default_timer() - start_time

# 测试TensorFlow函数的执行时间
start_time = timeit.default_timer()
_ = tf_simple_function(input_data)
elapsed_time_tf = timeit.default_timer() - start_time

print("Python function elapsed time:", elapsed_time_python)
print("TensorFlow function elapsed time:", elapsed_time_tf)


Python function elapsed time: 0.0015057999989949167
TensorFlow function elapsed time: 0.12585899999248795


In [13]:
import tensorflow as tf
import time

# 普通函数
def add(a, b):
    return a + b

# 使用 @tf.function 装饰的函数
@tf.function
def tf_add(a, b):
    return a + b

# 测试普通函数性能
start_time = time.time()
for _ in range(1000):
    result_add = add(1, 2)
end_time = time.time()
print("普通函数执行时间:", end_time - start_time)

# 测试经过 @tf.function 装饰的函数性能
start_time = time.time()
for _ in range(1000):
    result_tf_add = tf_add(1, 2)
end_time = time.time()
print("经过 @tf.function 装饰的函数执行时间:", end_time - start_time)


普通函数执行时间: 0.0002205371856689453
经过 @tf.function 装饰的函数执行时间: 0.3167226314544678


In [15]:
import tensorflow as tf
import time

# 普通函数
def matmul(a, b):
    return tf.matmul(a, b)

# 使用 @tf.function 装饰的函数
@tf.function
def tf_matmul(a, b):
    return tf.matmul(a, b)

# 生成一些随机矩阵
a = tf.random.normal((1000, 1000))
b = tf.random.normal((1000, 1000))

# 测试普通函数性能
start_time = time.time()
for _ in range(1000):
    result_matmul = matmul(a, b)
end_time = time.time()
print("普通函数执行时间:", end_time - start_time)

# 测试经过 @tf.function 装饰的函数性能
start_time = time.time()
for _ in range(1000):
    result_tf_matmul = tf_matmul(a, b)
end_time = time.time()
print("经过 @tf.function 装饰的函数执行时间:", end_time - start_time)


普通函数执行时间: 8.272811889648438
经过 @tf.function 装饰的函数执行时间: 8.67142629623413


In [3]:
import tensorflow as tf
import numpy as np

# 构造一个简单的图像数据
image = np.random.rand(1, 64, 64, 3)  # 一张64x64的RGB图像

# 构建只包含一个Conv2D层的模型
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=16, kernel_size=(3, 3), activation='relu', input_shape=(64, 64, 3))
])

# 获取Conv2D层的输出
conv_output = model.predict(image)

# 打印输入和输出
print("Input (Image):", image.shape)
print("Output (Conv2D):", conv_output.shape)

1/1 [==============================] - 0s 40ms/step


Input (Image): (1, 64, 64, 3)
Output (Conv2D): (1, 62, 62, 16)


In [7]:
import tensorflow as tf
import numpy as np

# 构造一个简单的图像数据
image = np.random.rand(1, 64, 64, 3)  # 一张64x64的RGB图像

# 构建包含Conv2D和MaxPooling2D层的模型
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=16, kernel_size=(3, 3), activation='relu', input_shape=(64, 64, 3)),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2))
])

# 获取池化层的输出
pooling_output = model.predict(image)

# 打印输入和输出
print("Input (Image):", image.shape)
print("Output (Conv2D + MaxPooling2D):", pooling_output.shape)


1/1 [==============================] - 0s 67ms/step
Input (Image): (1, 64, 64, 3)
Output (Conv2D + MaxPooling2D): (1, 31, 31, 16)


In [13]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[1.0, 2.0, 3.0]])

# 定义一个Dense层
dense_layer = tf.keras.layers.Dense(units=1, activation='relu')

# 将输入数据传递给Dense层
output_data = dense_layer(input_data)

# 打印输出
print("Input Data:", input_data.numpy())
print("Input Data shape:", input_data.shape)

print("Output Data (After Dense Layer):", output_data.numpy())
print("Input Data (After Dense Layer) shape:", output_data.shape)


Input Data: [[1. 2. 3.]]
Input Data shape: (1, 3)
Output Data (After Dense Layer): [[3.9061089]]
Input Data (After Dense Layer) shape: (1, 1)


In [15]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[1.0, 2.0, 3.0]])

# 定义一个Dense层，并在其后添加BatchNormalization层
batch_norm_layer = tf.keras.layers.BatchNormalization()

# 将输入数据传递给Dense层，然后通过BatchNormalization层
output_data = batch_norm_layer(input_data)

# 打印输出
print("Input Data:", input_data.numpy())
print("Output Data (After Dense + BatchNormalization):", output_data.numpy())


Input Data: [[1. 2. 3.]]
Output Data (After Dense + BatchNormalization): [[0.9995004 1.9990008 2.9985013]]


In [20]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[1.0, 2.0, 3.0]])

# 定义一个Dense层，并在其后添加Dropout层
dropout_layer = tf.keras.layers.Dropout(rate=0.5)

# 将输入数据传递给Dense层，然后通过Dropout层
output_data = dropout_layer(input_data, training=True)

# 打印输出
print("Input Data:", input_data.numpy())
print("Output Data (After Dropout):", output_data.numpy())


Input Data: [[1. 2. 3.]]
Output Data (After Dropout): [[0. 0. 6.]]


In [23]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[1.0, 2.0, 3.0]])

# 定义一个Dense层，并在其后添加Dropout层
dense_layer = tf.keras.layers.Dense(units=4, activation='relu')
dropout_layer = tf.keras.layers.Dropout(rate=0.5)

# 将输入数据传递给Dense层，然后通过Dropout层
output_data = dropout_layer(dense_layer(input_data), training=True)

# 打印输出
print("Input Data:", input_data.numpy())
print("Output Data (After Dense + Dropout):", output_data.numpy())


Input Data: [[1. 2. 3.]]
Output Data (After Dense + Dropout): [[4.078701  2.7408566 0.        0.       ]]


In [25]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[1, 2, 3, 4]])

# 定义一个Embedding层
embedding_layer = tf.keras.layers.Embedding(input_dim=5, output_dim=3, input_length=4)

# 将输入数据传递给Embedding层
output_data = embedding_layer(input_data)

# 打印输出
print("Input Data:", input_data.numpy())
print("Input Data shape:", input_data.shape)

print("Output Data (After Embedding):", output_data.numpy())
print("Output Data shape:", output_data.shape)


Input Data: [[1 2 3 4]]
Input Data shape: (1, 4)
Output Data (After Embedding): [[[ 0.0390268   0.03838977  0.03456748]
  [-0.02889923  0.03671585 -0.0343789 ]
  [-0.0006891   0.01629157 -0.02375256]
  [-0.04163213 -0.02001661  0.04961659]]]
Output Data shape: (1, 4, 3)


In [26]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])

# 定义一个全局平均池化层
global_avg_pooling_layer = tf.keras.layers.GlobalAveragePooling2D()

# 将输入数据传递给全局平均池化层
output_data = global_avg_pooling_layer(input_data)

# 打印输入和输出
print("Input Data:", input_data.numpy())
print("Output Data (After Global Average Pooling):", output_data.numpy())


ValueError: Input 0 of layer "global_average_pooling2d" is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: (1, 3, 3)

In [45]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]])
print("Input Data:", input_data.numpy())
print("Input Data:", input_data.shape)

# 添加一个维度来匹配GlobalAveragePooling2D的期望输入形状
input_data = tf.expand_dims(input_data, axis=0)

# 定义一个全局平均池化层
global_avg_pooling_layer = tf.keras.layers.GlobalMaxPooling2D()

# 将输入数据传递给全局平均池化层
output_data = global_avg_pooling_layer(input_data)

# 打印输入和输出
print("Input Data:", input_data.numpy())
print("Input Data:", input_data.shape)

print("Output Data (After Global Average Pooling):", output_data.numpy())
print("Output Data:", output_data.shape)


Input Data: [[[1. 2. 3.]
  [4. 5. 6.]]]
Input Data: (1, 2, 3)
Input Data: [[[[1. 2. 3.]
   [4. 5. 6.]]]]
Input Data: (1, 1, 2, 3)
Output Data (After Global Average Pooling): [[4. 5. 6.]]
Output Data: (1, 3)


In [44]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]])

# 定义一个卷积神经网络模型，包括卷积层和全局平均池化层
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(3, 3, 1)),
    tf.keras.layers.GlobalAveragePooling2D()
])

# 将输入数据传递给模型
output_data = model(input_data)

# 打印输入和输出
print("Input Data:", input_data.numpy())
print("Input Data Shape:", input_data.shape)
print("Output Data (After Global Average Pooling):", output_data.numpy())
print("Output Data Shape:", output_data.shape)


ValueError: Input 0 of layer "sequential_9" is incompatible with the layer: expected shape=(None, 3, 3, 1), found shape=(1, 2, 3)

In [33]:
import tensorflow as tf

# 构建一个简单的CNN模型
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(224, 224, 3)),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Conv2D(filters=128, kernel_size=(3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    tf.keras.layers.Conv2D(filters=256, kernel_size=(3, 3), activation='relu'),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax')
])

# 打印模型的结构
model.summary()


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 222, 222, 64)      1792      
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 111, 111, 64)     0         
 2D)                                                             
                                                                 
 conv2d_13 (Conv2D)          (None, 109, 109, 128)     73856     
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 54, 54, 128)      0         
 2D)                                                             
                                                                 
 conv2d_14 (Conv2D)          (None, 52, 52, 256)       295168    
                                                                 
 global_average_pooling2d_6   (None, 256)             

In [46]:
import tensorflow as tf

# 构造一些示例输入数据
input_data = tf.constant([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])

# 添加一个维度来匹配GlobalMaxPooling2D的期望输入形状
input_data = tf.expand_dims(input_data, axis=0)

# 定义一个全局最大池化层
global_max_pooling_layer = tf.keras.layers.GlobalMaxPooling2D()

# 将输入数据传递给全局最大池化层
output_data = global_max_pooling_layer(input_data)

# 打印输入和输出
print("Input Data:", input_data.numpy())
print("Output Data (After Global Max Pooling):", output_data.numpy())


Input Data: [[[[1. 2. 3.]
   [4. 5. 6.]
   [7. 8. 9.]]]]
Output Data (After Global Max Pooling): [[7. 8. 9.]]


In [41]:
import tensorflow as tf

# 构造两个示例输入数据
input_data1 = tf.constant([[1.0, 2.0, 3.0]])
input_data2 = tf.constant([[4.0, 5.0, 6.0]])

# 定义一个连接层
concatenate_layer = tf.keras.layers.Concatenate(axis=-1)

# 将两个输入数据传递给连接层
output_data = concatenate_layer([input_data1, input_data2])

# 打印输入和输出
print("Input Data 1:", input_data1.numpy())
print("Input Data 2:", input_data2.numpy())
print("Output Data (After Concatenation):", output_data.numpy())


Input Data 1: [[1. 2. 3.]]
Input Data 2: [[4. 5. 6.]]
Output Data (After Concatenation): [[1. 2. 3. 4. 5. 6.]]


In [43]:
import tensorflow as tf

# 构造两个示例输入数据
input_data1 = tf.constant([[1.0, 2.0, 3.0]])
input_data2 = tf.constant([[4.0, 5.0, 6.0]])

# 定义一个连接层，将在第二个维度上进行连接
concatenate_layer = tf.keras.layers.Concatenate(axis=0)

# 将两个输入数据传递给连接层
output_data = concatenate_layer([input_data1, input_data2])

# 打印输入和输出
print("Input Data 1:", input_data1.numpy())
print("Input Data 2:", input_data2.numpy())
print("Output Data (After Concatenation):", output_data.numpy())


Input Data 1: [[1. 2. 3.]]
Input Data 2: [[4. 5. 6.]]
Output Data (After Concatenation): [[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
input_data1.shape

TensorShape([1, 3])

In [1]:
# 定义表格中的数据
data = {
    "female": {"treatment_A_remission": 50, "treatment_A_no_remission": 50, "treatment_B_remission": 220, "treatment_B_no_remission": 180},
    "male": {"treatment_A_remission": 300, "treatment_A_no_remission": 100, "treatment_B_remission": 80, "treatment_B_no_remission": 20}
}

# 计算女性的比值比（Odds Ratio）
OR_female = (data["female"]["treatment_A_remission"] / data["female"]["treatment_A_no_remission"]) / (data["female"]["treatment_B_remission"] / data["female"]["treatment_B_no_remission"])

# 计算男性的比值比（Odds Ratio）
OR_male = (data["male"]["treatment_A_remission"] / data["male"]["treatment_A_no_remission"]) / (data["male"]["treatment_B_remission"] / data["male"]["treatment_B_no_remission"])

OR_female, OR_male


(0.8181818181818181, 0.75)

In [2]:
from scipy.stats import chi2_contingency
import numpy as np

# 首先，我们需要构建边际表
# 从原始数据中提取总体的缓解和未缓解的人数，不分性别
total_remission_A = data["female"]["treatment_A_remission"] + data["male"]["treatment_A_remission"]
total_no_remission_A = data["female"]["treatment_A_no_remission"] + data["male"]["treatment_A_no_remission"]
total_remission_B = data["female"]["treatment_B_remission"] + data["male"]["treatment_B_remission"]
total_no_remission_B = data["female"]["treatment_B_no_remission"] + data["male"]["treatment_B_no_remission"]

# 边际表
marginal_table = np.array([[total_remission_A, total_no_remission_A], 
                            [total_remission_B, total_no_remission_B]])

# 计算边际比值比
marginal_OR = (marginal_table[0][0] / marginal_table[0][1]) / (marginal_table[1][0] / marginal_table[1][1])

# 计算χ²检验，以判断辛普森悖论
chi2, p, dof, ex = chi2_contingency(marginal_table)

# 使用χ²检验的结果计算男性部分比值比的95%置信区间
# 计算标准误差 (se) 和 z值 (z_value)
se = np.sqrt(1/total_remission_A + 1/total_no_remission_A + 1/total_remission_B + 1/total_no_remission_B)
z_value = 1.96  # 对应95%置信区间的z值

# 男性的部分比值比 (OR_male) 已经在上一个计算中得出
# 计算置信区间的对数变换
log_OR_male = np.log(OR_male)
conf_interval_log = [log_OR_male - z_value * se, log_OR_male + z_value * se]

# 将对数置信区间转换回原始比值比
conf_interval_OR_male = np.exp(conf_interval_log)

marginal_OR, marginal_table, p, conf_interval_OR_male


(1.5555555555555556,
 array([[350, 150],
        [300, 200]]),
 0.001159465691351218,
 array([0.57718174, 0.97456306]))

In [3]:
346 + 386 + 338 + 380 + 418 + 401 + 373 + 371 + 437 + 427

3877

In [12]:
import scipy.stats as stats

# 数据
thefts_by_year = [346, 386, 338, 380, 418, 401, 373, 371, 437, 427]

# 计算全体均值
mean_total = sum(thefts_by_year) / len(thefts_by_year)

# 计算组间平方和 (SSB)
ssb = sum((1 * (x - mean_total) ** 2) for x in thefts_by_year)

# 计算组内平方和 (SSW)
ssw = sum((x - ) ** 2 for x in thefts_by_year)

# 计算自由度
df_b = len(thefts_by_year) - 1
df_w = len(thefts_by_year) - 1

# 计算均方
msb = ssb / df_b
msw = ssw / df_w

# 计算F值
f_statistic = msb / msw

# 输出结果
print("Mean Total:", mean_total)
print("SSB:", ssb)
print("SSW:", ssw)
print("df_B:", df_b)
print("df_W:", df_w)
print("MSB:", msb)
print("MSW:", msw)
print("F-statistic:", f_statistic)


Mean Total: 387.7
SSB: 9836.1
SSW: 9836.1
df_B: 9
df_W: 9
MSB: 1092.9
MSW: 1092.9
F-statistic: 1.0


In [9]:
msw

0.0

In [10]:
df_w

9

In [11]:
ssw

0

In [1]:
from tensorflow.keras.utils import to_categorical
import numpy as np
from tensorflow.keras.layers import Input, Embedding, Flatten, Dense, Dot
from tensorflow.keras.models import Model
import tensorflow as tf

# 定义超参数
vocab_size = 100  # 词汇表大小
embedding_dim = 8  # 嵌入维度
max_length = 10  # 输入序列的最大长度
num_samples = 1000  # 样本数量

# 生成模拟数据
np.random.seed(42)
# 生成查询和文档的随机序列
query_sequences = np.random.randint(1, vocab_size, size=(num_samples, max_length))
doc_sequences = np.random.randint(1, vocab_size, size=(num_samples, max_length))
# 生成标签，随机选择一部分为正样本（相似），其余为负样本（不相似）
labels = np.random.randint(2, size=(num_samples, 1))

# 构建模型
query_input = Input(shape=(max_length,), dtype='int32')
doc_input = Input(shape=(max_length,), dtype='int32')

embedding_layer = Embedding(input_dim=vocab_size, output_dim=embedding_dim, name='shared_embedding')

query_embedding = embedding_layer(query_input)
doc_embedding = embedding_layer(doc_input)

query_flat = Flatten()(query_embedding)
doc_flat = Flatten()(doc_embedding)

query_dense = Dense(64, activation='relu')(query_flat)
doc_dense = Dense(64, activation='relu')(doc_flat)

dot_similarity = Dot(axes=1, normalize=True)([query_dense, doc_dense])

model = Model(inputs=[query_input, doc_input], outputs=dot_similarity)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 模型概况
model.summary()

# 拟合模型
history = model.fit([query_sequences, doc_sequences], labels, batch_size=32, epochs=10, validation_split=0.1)

history.history


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 10)]         0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 10)]         0           []                               
                                                                                                  
 shared_embedding (Embedding)   (None, 10, 8)        800         ['input_1[0][0]',                
                                                                  'input_2[0][0]']                
                                                                                                  
 flatten (Flatten)              (None, 80)           0           ['shared_embedding[0][0]']   

{'loss': [0.7745499610900879,
  0.6415559649467468,
  0.596912145614624,
  0.5623939037322998,
  0.5328953862190247,
  0.5056374073028564,
  0.4810194671154022,
  0.457234263420105,
  0.4347202181816101,
  0.4130679666996002],
 'accuracy': [0.47111111879348755,
  0.653333306312561,
  0.7733333110809326,
  0.8277778029441833,
  0.8644444346427917,
  0.8999999761581421,
  0.9244444370269775,
  0.9300000071525574,
  0.9433333277702332,
  0.9466666579246521],
 'val_loss': [0.7359145879745483,
  0.7102096676826477,
  0.7058979868888855,
  0.7152442336082458,
  0.7212607860565186,
  0.7312759160995483,
  0.7309934496879578,
  0.7455120086669922,
  0.7548627257347107,
  0.7592551708221436],
 'val_accuracy': [0.4399999976158142,
  0.47999998927116394,
  0.49000000953674316,
  0.47999998927116394,
  0.44999998807907104,
  0.4699999988079071,
  0.5,
  0.49000000953674316,
  0.4399999976158142,
  0.46000000834465027]}

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Dense, Flatten, Dot
from tensorflow.keras.optimizers import Adam


In [3]:
# 设置随机种子以确保可复现性
np.random.seed(42)

# 定义参数
num_users = 1000
num_items = 1000
embedding_size = 30

# 生成用户和物品的ID
user_ids = np.random.randint(0, num_users, size=(10000, 1))
item_ids = np.random.randint(0, num_items, size=(10000, 1))

# 随机生成标签（这里简化为0或1，表示用户对物品的喜好）
labels = np.random.randint(2, size=(10000, 1))


In [4]:
# 定义输入
user_input = Input(shape=(1,), name='user_input')
item_input = Input(shape=(1,), name='item_input')

# 定义嵌入层
user_embedding = Embedding(num_users, embedding_size, input_length=1, name='user_embedding')(user_input)
item_embedding = Embedding(num_items, embedding_size, input_length=1, name='item_embedding')(item_input)

# 扁平化嵌入向量
user_vec = Flatten(name='flatten_user')(user_embedding)
item_vec = Flatten(name='flatten_item')(item_embedding)

# 计算用户向量和物品向量的点积
merged = Dot(name='dot_product', normalize=True, axes=1)([user_vec, item_vec])

# 定义模型
model = Model(inputs=[user_input, item_input], outputs=merged)

# 编译模型
model.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])

# 模型概览
model.summary()


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 user_input (InputLayer)        [(None, 1)]          0           []                               
                                                                                                  
 item_input (InputLayer)        [(None, 1)]          0           []                               
                                                                                                  
 user_embedding (Embedding)     (None, 1, 30)        30000       ['user_input[0][0]']             
                                                                                                  
 item_embedding (Embedding)     (None, 1, 30)        30000       ['item_input[0][0]']             
                                                                                            

In [9]:
model.fit([user_ids, item_ids], labels, batch_size=64, epochs=10, validation_split=0.1)


Epoch 1/10
141/141 [==============================] - 0s 3ms/step - loss: 2.8602 - accuracy: 0.7430 - val_loss: 4.4700 - val_accuracy: 0.5030
Epoch 2/10
141/141 [==============================] - 0s 3ms/step - loss: 2.7309 - accuracy: 0.7641 - val_loss: 4.5148 - val_accuracy: 0.5030
Epoch 3/10
141/141 [==============================] - 0s 2ms/step - loss: 2.6253 - accuracy: 0.7796 - val_loss: 4.4676 - val_accuracy: 0.5030
Epoch 4/10
141/141 [==============================] - 0s 2ms/step - loss: 2.5350 - accuracy: 0.7904 - val_loss: 4.5717 - val_accuracy: 0.5050
Epoch 5/10
141/141 [==============================] - 0s 2ms/step - loss: 2.4618 - accuracy: 0.8034 - val_loss: 4.6018 - val_accuracy: 0.5050
Epoch 6/10
141/141 [==============================] - 0s 2ms/step - loss: 2.3852 - accuracy: 0.8121 - val_loss: 4.5882 - val_accuracy: 0.5050
Epoch 7/10
141/141 [==============================] - 0s 3ms/step - loss: 2.3094 - accuracy: 0.8183 - val_loss: 4.5387 - val_accuracy: 0.5050
Epoch 

In [14]:
# 生成物品的ID序列
item_ids_for_prediction = np.arange(num_items).reshape(-1, 1)

# 预测用户对所有物品的兴趣
predictions = model.predict([np.ones_like(item_ids_for_prediction) * 1, item_ids_for_prediction])

# 获取预测兴趣最高的前10个物品
top_10_items = predictions.flatten().argsort()[-10:][::-1]

print(f"推荐给用户1的前10个物品ID: {top_10_items}")


32/32 [==============================] - 0s 2ms/step
推荐给用户1的前10个物品ID: [934 425 677 240 773 362 149 447 679 665]


是的，DSSM（Deep Structured Semantic Model，深度结构化语义模型）可以被视为一种“双塔”（Two-Tower）模型的早期例子。在双塔模型中，两个独立的神经网络（称为“塔”）分别处理两种不同类型的输入数据，通常是用户和物品的特征。这两个网络通常结构相似但是参数独立，它们的目标是将输入特征转换成嵌入向量（即低维稠密向量），这些嵌入向量随后被用来计算两个输入间的相似度或者相关性得分。

### DSSM的双塔结构

在DSSM中，一个“塔”处理查询（例如，用户的搜索查询），另一个“塔”处理文档（例如，网页或广告）。每个塔通常包括多层全连接网络，用于学习输入文本的深层语义表示。最终，两个塔的输出（即，查询和文档的嵌入向量）通过余弦相似度（或其他相似度度量）来计算它们之间的相似性。

### 双塔模型的关键特点

- **独立的特征学习**：两个塔独立学习输入数据的表示，这使得模型能够灵活处理不同类型的数据并学习它们的深层语义。
- **相似度计算**：通过计算两个嵌入向量的相似度，双塔模型能够评估两个输入之间的关系，这对于推荐系统、信息检索和许多其他应用非常重要。
- **可扩展性**：双塔模型特别适合大规模应用，因为一旦嵌入向量被计算出来，就可以高效地在大量候选中进行匹配和检索。

### 应用

DSSM及其变体在推荐系统、信息检索、自然语言处理等领域有广泛应用。双塔模型的一个关键优势是它们可以被预先训练和索引，从而在实际应用中实现快速的检索和匹配。

总的来说，DSSM是双塔模型概念的早期实现之一，它展示了深度学习在理解文本语义相似度方面的强大能力。随着技术的发展，许多基于DSSM的改进和扩展模型已经被提出，进一步提高了模型的性能和应用范围。

DSSM（Deep Structured Semantic Model），即深度结构化语义模型，是一种基于深度学习的语义匹配模型，最早由微软研究院提出。它主要用于处理文本相似度计算问题，广泛应用于搜索引擎的相关性匹配、推荐系统中的内容推荐、自然语言处理领域的语义理解等任务。

### 原理和架构

DSSM模型的核心思想是将文本（如查询和文档）通过深度神经网络转换成低维稠密向量，也称为语义向量，然后通过计算这些向量之间的相似度（如余弦相似度）来评估文本之间的语义相似度。

DSSM的基本架构通常包含以下几个步骤：

1. **文本表示**：首先将原始文本转换为词向量，常用的方法包括词袋模型、One-hot编码等。

2. **深度神经网络**：通过一个或多个隐藏层将词向量转换为低维的语义向量。这些隐藏层可以是全连接层，也可以是卷积神经网络(CNN)或循环神经网络(RNN)等结构。

3. **相似度计算**：最后，使用余弦相似度或其他相似度度量方式来计算两个语义向量的相似度。

### 训练过程

在训练过程中，DSSM使用负采样的方式来提升模型的区分能力。具体来说，对于一个正样本（查询和相关文档的对），会随机选择若干个负样本（查询和不相关文档的对）。模型的目标是最大化正样本的相似度，同时最小化负样本的相似度。

模型通常使用交叉熵损失函数来进行训练，优化的目标是提升正样本的预测概率，降低负样本的预测概率。

### 应用和优点

DSSM模型在处理文本相似度和语义匹配问题时具有明显的优势，能够有效捕捉文本的深层语义信息。它在搜索引擎的查询-文档匹配、推荐系统中的用户兴趣匹配、以及自然语言处理的多种任务中都有广泛的应用。

### 缺点

尽管DSSM在语义理解方面表现出色，但它也存在一些局限性，比如对高维稀疏输入的处理效率较低，以及模型训练和调参相对复杂等问题。此外，随着深度学习技术的发展，后续有许多模型在DSSM的基础上进行了改进和优化，如使用更复杂的网络结构（比如Transformer）来进一步提升模型的性能。

处理 Apache Spark 中的数据倾斜问题是一个常见但复杂的挑战。数据倾斜指的是在分布式计算过程中，数据不均匀地分配在不同的节点上，导致部分节点工作量过大，而其他节点则相对空闲，进而影响整个作业的处理效率。以下是一些常用的方法来处理 Spark 中的数据倾斜：

1. **增大并行度**：
   - 通过调整`spark.sql.shuffle.partitions`（对于 DataFrame API）或`spark.default.parallelism`（对于 RDD API）的配置来增加任务的并行度，从而有更多的分区来分散数据，减轻倾斜。

2. **过滤无用数据**：
   - 在数据处理前尽可能过滤掉不需要的数据，减少数据量可以在一定程度上缓解数据倾斜。

3. **采用随机前缀**：
   - 对倾斜的键添加随机前缀，使其分散到不同的分区中。处理完成后再去除这些前缀。这种方法适用于倾斜键值过多的情况。

4. **扩展倾斜键**：
   - 对于倾斜严重的键，可以将其拆分成多个键，使其能够均匀分布到不同的分区中。

5. **使用广播变量**：
   - 如果数据倾斜是由于小表和大表的JOIN操作导致的，可以考虑将小表广播出去，这样就不需要对大表进行shuffle操作，从而避免了数据倾斜。

6. **重分区（Repartition）或者增加分区数（Coalesce）**：
   - 使用`repartition`方法可以根据键值重新分配数据，有助于数据更均匀地分布。`coalesce`方法则在减少分区数时避免全局shuffle，但可以在增加分区数时使用`repartition`来重新分配数据。

7. **自定义分区器**：
   - 如果默认的分区方式不能有效地处理数据倾斜，可以考虑实现自定义分区器，根据数据的实际分布来分配键值到不同的分区中。

8. **对倾斜键进行采样**：
   - 分析数据分布，对倾斜的键进行采样，然后根据采样结果调整数据处理逻辑，比如通过对倾斜键分割处理等方式来减轻倾斜。

9. **限制笛卡尔积操作**：
   - 避免使用会产生大量数据的操作，如笛卡尔积（Cartesian product），因为这些操作很容易产生数据倾斜。

处理数据倾斜是一个需要根据具体情况来定制解决方案的过程。通常，识别倾斜的来源并对其进行针对性的优化是解决问题的关键。实践中，可能需要结合多种方法来有效地缓解数据倾斜问题。